### ISSUE TITLE
Slate Redstone Ore bug

### ISSUE THREAD

**Issue by EleReeNe** [BlueStaggo/MCDiverge#1]
When i hit Slate Redstone ore it starts releasing it's particles like normal redstone ore, but when the particles stop it becomes an normal redstone ore.

https://user-images.githubusercontent.com/121627740/209976795-a74c02fb-13fc-412f-9b33-6a1430c5a05b.mp4

**Comment by BlueStaggo** [comment]
I already know of this bug and it will be patched in Minecraft Diverge v0.1.1 or v0.2 if I feel like it.

**Comment by BlueStaggo** [comment]
Fixed in Minecraft Diverge v0.1.1. Releasing soon.
https://user-images.githubusercontent.com/71090710/211060161-10b38772-93e3-4456-9d79-c9621f5c38f8.mp4
