### ISSUE TITLE
Cannot launch server Alpha v1.1.2_01

### ISSUE THREAD

**Issue by lemmings189** [BlueStaggo/MCDiverge#15]
Hello,
Is it still possible to download Minecraft Alpha v1.1.2_01 (a0.2.1) server on the Minecraft Launcher ? I cannot see the little button to download the server jar ?!

Does anyone has a solution ? Or perhaps could send me the jar ?
Thanks a lot,

**Comment by lemmings189** [comment]
Seems that Microsoft removed it: https://launcher.mojang.com/v1/objects/daa4b9f192d2c260837d3b98c39432324da28e86/server.jar
redirects to nothing

**Comment by lemmings189** [comment]
Here is also only the client: https://mcversions.net/download/a1.1.2_01

**Comment by lemmings189** [comment]
Alr found it here: https://archive.org/details/old_minecraft_jars_archive but now I have anOTHER problem,
After the installation process (copying files from Diverge_server to the server_1.1.2_01.jar)
the server opens and suddenly closes by itself, however it generated the basic files (world, properties...)

but, the log says:
2023-08-01 19:08:04 [INFO] Starting Minecraft Diverge server version 0.2.2_01
2023-08-01 19:08:04 [INFO] Loading properties
2023-08-01 19:08:04 [INFO] Starting Minecraft server on *:25565
2023-08-01 19:08:04 [INFO] Preparing level "world"
2023-08-01 19:08:04 [INFO] Preparing start region
2023-08-01 19:08:04 [INFO] Stopping server

**Comment by KaseyTheJackal** [comment]
Grab the one from Betacraft's servers. That worked for me!

**Comment by lemmings189** [comment]
> Grab the one from Betacraft's servers. That worked for me!

Where do you find it ? Inside the launcher ?

**Comment by lemmings189** [comment]
Just found it ! https://betacraft.uk/server-archive/
Thanks !
