### ISSUE TITLE
Cobblestone stairs giving different stone upon mining

### ISSUE THREAD

**Issue by Mrmanguyalone** [BlueStaggo/MCDiverge#2]
Cobblestone stairs give different variants of cobblestone when dropped in different directions. Not sure if this affects all stairs as I've only tested it with cobblestone as of the moment.

https://user-images.githubusercontent.com/107666897/210290845-33d22c5c-a3f0-4f0e-ba27-39e1a9e0e1cc.mp4

**Comment by BlueStaggo** [comment]
This bug is fixed in Minecraft Diverge v0.1.1, which will be released soon.
