### ISSUE TITLE
Destroying a block under a red torch causes a crash.

### ISSUE THREAD

**Issue by Andrey04o** [BlueStaggo/MCDiverge#21]
https://github.com/BlueStaggo/MCDiverge/assets/53095919/f2b3fada-e4eb-47ce-8282-298c33ba6f4e

**Comment by Andrey04o** [comment]
Sorry for my English

**Comment by Andrey04o** [comment]
Water is not required. Just removing a block will cause this problem.

**Comment by YTXSY** [comment]
国人？
在GitHub找到了这玩意玩还提交了issues
稀有捏（

**Comment by Andrey04o** [comment]
> 国人？

No, I'm from Russia.

**Comment by BlueStaggo** [comment]
Fixed in 0.3.1
