### ISSUE TITLE
MC Diverge crashes when I open the game

### ISSUE THREAD

**Issue by DarkDust95** [BlueStaggo/MCDiverge#25]
I just added MC Diverge to Betacraft launcher, and for some reason it it just crashes. Here is what it says.

      Minecraft has crashed!      
      ----------------------      

Minecraft has stopped running because it encountered a problem.

If you wish to report this, please copy this entire text and email it to support@mojang.com.
Please include a description of what you did when the error occured.

// You're mean.
--- BEGIN ERROR REPORT 37d40b4e --------
Generated 29.11.23 21:12

Minecraft: Minecraft Diverge 0.3.1.1
OS: Windows 10 (amd64) version 10.0
Java: 1.8.0_391, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.3
OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 version 4.6.0 NVIDIA 536.67, NVIDIA Corporation

java.lang.NumberFormatException: For input string: "NORMAL"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at fr.a(GameSettings.java:445)
	at fr.<init>(GameSettings.java:83)
	at net.minecraft.client.Minecraft.a(Minecraft.java:223)
	at net.minecraft.client.Minecraft.run(Minecraft.java:453)
	at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 6f6e875f ----------

How can I fix it? (I can't use other launchers, only Betacraft)

**Comment by BlueStaggo** [comment]
Closed: This is due to the buggy nature of the pre-beta rework branch of Diverge which is no longer supported.
