### ISSUE TITLE
Tile entities do not properly retain their information on chunk reload/generation

### ISSUE THREAD

**Issue by wonderstarcomet** [BlueStaggo/MCDiverge#27]
I played for around two hours tonight and was far away from my base where I had placed roughly five items in a chest near my bed. I believe I was far enough away from my base for it to unload.

I died and respawned at my bed, and then opened my chest. All of the items I had put in the chest had completely disappeared. I checked the game log and NBTExplorer but could not find any traces of any error happening.

Strangely, but seemingly related; I stumbled across a mob spawner in a deep cave, It was a pig spawner and both dungeon chests were unloaded.

Sorry I don't have the world file for debugging purposes, I deleted the instance completely in a fit of anger.

Should clarify; this is in the latest beta release of Diverge ([1.0-a9](https://github.com/BlueStaggo/MCDiverge/releases/tag/1.0-a9))

**Comment by BlueStaggo** [comment]
I have absolutely no idea what the heck is happening????
This has always been an issue and I have absolutely no idea why tile entities are getting erased.

**Comment by wonderstarcomet** [comment]
My only guess is that you have made some kind of internal change to chunking that causes tile entities to not properly serialize their contents when a chunk is unloaded and reloaded. It's the only explanation I can think of for why generated dungeon chests bug out and get erased. Ostensibly this seems to apply to ALL tile entities, judging by the spawner bugging out too.

I've cooled off and am going to redownload and screw around tonight to see if I can get a reproduction consistently.

**Comment by BlueStaggo** [comment]
Fixed in 1.0-a9.3

**Comment by wonderstarcomet** [comment]
Thank you!
