### ISSUE TITLE
Other types of sapling drop an oak sapling upon breaking

### ISSUE THREAD

**Issue by aubymori** [BlueStaggo/MCDiverge#3]
https://user-images.githubusercontent.com/44238627/219876088-c8448066-cb73-4717-a21d-5d1a75034b3f.mp4

**Comment by BlueStaggo** [comment]
I knew I should have had my doubts about saplings! I'll fix those saplings when I can. Expect a v0.2.0_01 update soon.

**Comment by BlueStaggo** [comment]
Fixed in the upcoming v0.2.0_01 update.
