### ISSUE TITLE
Spammed step sounds when jumping on non-full block

### ISSUE THREAD

**Issue by aubymori** [BlueStaggo/MCDiverge#4]
https://user-images.githubusercontent.com/44238627/219876226-fb267ad1-abf7-4bdd-a6e0-aab07470999f.mp4

**Comment by BlueStaggo** [comment]
This just so happens to be similar to a bug I tried to fix! I will look into this ASAP.

**Comment by BlueStaggo** [comment]
Fixed in the upcoming v0.2.0_01 update.
