### ISSUE TITLE
Slate Iron Ore Does Not Smelt In Furnace

### ISSUE THREAD

**Issue by Mrmanguyalone** [BlueStaggo/MCDiverge#5]
Not sure if this is intended or not, but it seems slate iron ore doesn't smelt inside furnaces, I haven't tried the blaster yet to see if it has a similar issue.

https://user-images.githubusercontent.com/107666897/220140950-69eb07b6-e145-4a61-9d3a-8f8438652395.mp4

**Comment by BlueStaggo** [comment]
Ore smelting seems to work just fine for me, so I don't know what the problem is. I've heard of a similar issue where someone was unable to smelt cobbled marble. Can you try reinserting the ore and coal?

**Comment by Mrmanguyalone** [comment]
After a game restart the issue is properly fixed now. Not sure why it wasn't working before. I guess just weird alpha code as always lol.

**Comment by bluebear94** [comment]
Seems to happen whenever you open the recipe book.

**Comment by BlueStaggo** [comment]
I have figured that out by myself and that is fixed in the v0.2.1 update coming today. I just happened to figure it out while improving the recipe guide itself!
