### ISSUE TITLE
Can I transfer this item to the MCBBS forum?

### ISSUE THREAD

**Issue by laoqijun1** [BlueStaggo/MCDiverge#9]
MCBBS forum is one of the largest Minecraft forums in China, and I hope to post it to let more people know about this excellent integration.

**Comment by BlueStaggo** [comment]
As long as you credit me and keep the post up to date, I don't really see a problem with that. You may go ahead.

**Comment by laoqijun1** [comment]
> As long as you credit me and keep the post up to date, I don't really see a problem with that. You may go ahead.

OK!
